###服务器端口号
server:
  port: 8081
###dubbo注册到注册中心的名称
dubbo:
  application:
    name: member
    ###采用的协议方式和端口号
  protocol:
    name: dubbo
    port: 20881
  registry:
  ###dubbo注册中心地址
    address: zookeeper://127.0.0.1:2181
#  scan:
#  ###dubbo 实现类扫包范围
#    base-packages: com.member